mod "ntp",
    :git => "git://github.com/puppetlabs/puppetlabs-ntp.git"

mod "jenkins",
    :git => "git://github.com/jenkinsci/puppet-jenkins.git"

mod "apt",
    :git => "git://github.com/puppetlabs/puppetlabs-apt.git"

mod "stdlib",
    :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"

mod "virtualbox",
    :git => "git://github.com/smarchive/puppet-virtualbox.git"
